### ISSUE TITLE
EyeDropper Not woring in Pdf, Images

### ISSUE THREAD

**Issue by Aakash30Sethiya** [kepi/chromeEyeDropper#100]
EyeDropper Not working in Pdf, Images, and so on except web pages which are running. And also asked on every single selection "Pick from Web Pages". Why this is always shows this popup. The chrome eye dropper don't work like that. it should work like "when I click on extention it just pick the color from the opened browser, doesn't matter what kind of page is opened. and also not asked me pick from web page or not, because the eyedropper doesn't pick color from the other window or another application."

Hope You May notice this point.

!thanks in advance....

**Comment by kepi** [comment]
Thanks for your report.

As for first issue - for PDF it is usually working on first page until you try to scroll. I do not plan to support picking colors from PDF more than this, sorry. Picking color from Image is working without any problem, not sure what are you referring to.

Second issue - this is by design, many people use history part of Eye Dropper and not only picking actual color. You can set keyboard shortcut to pick color which will work without need to open popup with selection. You can check issue #18
