### ISSUE TITLE
Ruined Click Ability on Chrome OSX

### ISSUE THREAD

**Issue by WeyrleaderZor** [kepi/chromeEyeDropper#105]
I had tried this to help pick colors for a site I was working on and prior to this, everything worked well. After installing this, the clicking behavior is HORRIBLY BROKEN even after removing the extension- particularly on FB. The "like" link does not work (the page jumps up as though I pressed page up), the "notifications" and "messages" buttons do not respond to clicks. 
NONE of this happened before putting this extension on the browser- and other profiles that never had it still work just fine… This extension was the ONLY thing different. PLEASE look into this- it's unacceptable for an extension to ruin standard browser behavior- and to an extent that even removing it does not undo whatever it does.

**Comment by kepi** [comment]
Hi, I'm sorry about your troubles. It is impossible for extension to change any behavior of your browser after you uninstall it (in case you restarted browser after to be double sure).

Extensions lives only in one sub directory in your chrome profile and when you uninstall them, folder is deleted and there is simply now way how they can interact with your browser any more.

Behaviour you are describing shouldn't be caused by Eye Dropper at all. It is not interacting with mouse clicks untill you activate it (either by using extension icon or shortcut). You can review your shortcuts if you go to `chrome://extensions/` page and click on keyboard shortcuts link at the bottom of the page.

Next thing you can try is to use FB and others in anonymous mode where all extensions are blocked (if you didn't allow them explicitly). If it is still broken, it is possible that you have something wrong elsewhere.

I understand that it seams like only thing different was eye dropper extension but it is very unlikely it caused something like you are describing and totally impossible to do if you uninstalled it.
