### ISSUE TITLE
Can't pick colors from Google slides

### ISSUE THREAD

**Issue by maengu9** [kepi/chromeEyeDropper#117]
Hello, guys

For some reason I can't pick colors from presentation in Google Slides (or Google Docs or Google Sheets or pretty much any of the Google sites). I can still pick a color from other web pages though. Is there a chance this will ever work for Google sites?

Thank you

**Comment by kepi** [comment]
Hey @maengu9 its really weird as it should work without any problem. Can you give me little more detail about your environment? What operating system are you using and which version of Google Chrome?

Also is there any publicly available document in which it is not working for you so I can try to reproduce here? I tried slides, sheets and document now and all is working without any glitch.

**Comment by kepi** [comment]
Closing the issue because there has been no response to request for more information from the original author. With only the information that is currently in the issue, I don't have enough information to take action. Please reach out if you have or find the answers I need so  that I can investigate further.
