### ISSUE TITLE
girl that is NOT brown 

### ISSUE THREAD

**Issue by doppioscursedaccount** [kepi/chromeEyeDropper#192]
![image](https://user-images.githubusercontent.com/60762078/139757994-6a85ed8b-fcb3-4aaf-9c95-dfb6810eb054.png)

**Comment by kepi** [comment]
I hear ya. It's same trouble as with `#b25`. That color is totally not `#b25`, it is just closest short color.

As for named colors - library is guessing closest color, but it would be better to have this clearly separated. Option to have exact color names only could be nice too.

Anyway, it might be beneficial to adjust closest color guessing too (this issue should be filled in external library I'm using). Because when talking aproximations, I would guess this more red than brown.
