### ISSUE TITLE
Rewritten Eye Dropper - testing and feedback needed

### ISSUE THREAD

**Issue by kepi** [kepi/chromeEyeDropper#256]
I'm almost ready to publish rewrite of Eye Dropper with many fixes and UI improvements.

But as this is huge change, I would like to test it more and get some feedback. If you have time, please help me test it:

**Beta version is now published at [chrome store](https://chromewebstore.google.com/detail/eye-dropper-beta/ddepepfaephbkpjkhbjecikldgpnojjl)** so it is enough to just add it as normal extension.

I'll gladly accept any feedback, bug reports etc. You can spam this issue or create new ones for specific troubles if not reported already.

**Comment by NeonBeacon** [comment]
Hi Kepi,

The functionality works well, although my intitial thought was that it hadn't worked.

- This time when selecting 'web page' the mouse icon changed and you could see a small box indicating the colour the mouse is hovering over (perfect, smiley face)

- (This is where the process confused me) I had clicked on the colour, the icon disappeared, my first idea was to ctrl + v  to paste the hex code or rgb number as it may have copied it from the colour. I only did this as I'm used to that functionality in blender or adobe, unsure if other users would also assume this. 

- I tried the same process again, not realising it had saved the colour in the 'selected' box once I selected colour picker again. (This is likely my fault for not reading how to use the extension, but potentially food for thought regardless).

- 3rd time round I realised where the colour stores and shows the codes for the colours and where to copy them for usage.

- As the extension box disappears after you select 'from webpage' (which is understandable so to be able to select anything on the webpage) you don't see the code saved until you click back into the extension, which can be confusing using the extension for the first time. 

The only potential critique for functionality would be to have that set as ticked as standard when someone installs the extension. But again, that might just be my preference rather than anything else.

The only other area I would mention, with a design background, only cosmetic, regarding the extension drop down frame,slightly rounded edges to the drop down box would be less harsh, and the font for the 'hex', 'code', 'rgb', 'hsl', 'hsv', 'New', 'Selected', 'Pick from', 'Hover over colors to preview a color in New square' and the 'linear-gradient' text could be prettier. But again, the cosmetics for such a good tool aren't that important.

**Comment by kepi** [comment]
Thanks for detailed walk through, it helps me rethink on my past decissions.

> The only potential critique for functionality would be to have that set as ticked as standard when someone installs the extension. But again, that might just be my preference rather than anything else.

I'll probably go with your suggestion. My reasoning had been that I shouldn't rewrite content of user clipboard without his consent first, but that was many many years ago and I think it really adds to the confusion. Workaround would be some annoying popup which will tell on first use what to do, but I'll probably just set it as default.

> The only other area I would mention, with a design background, only cosmetic, regarding the extension drop down frame,slightly rounded edges to the drop down box would be less harsh, and the font for the 'hex', 'code', 'rgb', 'hsl', 'hsv', 'New', 'Selected', 'Pick from', 'Hover over colors to preview a color in New square' and the 'linear-gradient' text could be prettier. But again, the cosmetics for such a good tool aren't that important.

Can you please give me screenshot how it looks like on your computer? IMHO fonts I'm using are OS specific, so I just want to check if it is looking too different from what I wanted.

**Comment by NeonBeacon** [comment]
![image](https://github.com/kepi/chromeEyeDropper/assets/129503880/a5a3a663-4d55-4275-b5c6-001cbaf277e5)

Hi Kepi,

Here's the screenshot of how it looks on my PC

**Comment by NeonBeacon** [comment]
Sorry for the delay, couldn't get to my computer for a couple of days, I've
posted on Github

**Comment by kepi** [comment]
@NeonBeacon that screenshot is definitely from old version :) Did you try it with extension loaded from zip?

I just uploaded latest fixes with new zip, and hopefully by tomorrow, new beta version would be available from store too (check if it is version 1.3.5.0 or greater): https://chromewebstore.google.com/detail/eye-dropper-beta/ddepepfaephbkpjkhbjecikldgpnojjl

Anyway I'm reasonably sure it will work, so I'll try to upgrade prod version too when it is checked by chrome team.

**Comment by NeonBeacon** [comment]
Yep, I've now got the new version, all works, and it's looking good!

![image](https://github.com/kepi/chromeEyeDropper/assets/129503880/f2943189-61ae-4b3a-9476-b4433cb1e0ef)

That was my mistake on the previous screenshot.

**Comment by kepi** [comment]
Great and thanks for confirmation. I published new version today for 10 % of users and I hope to gather bug reports if there is some problem, we will see. Thanks again for help.

**Comment by BuBuStuff** [comment]
I tested it on the Opera browser, and it works PERFECTLY! Glad to see the bugs have been fixed :D
