### ISSUE TITLE
Недоречний колір текста та кнопок в секції Pick from

### ISSUE THREAD

**Issue by maximus2526** [kepi/chromeEyeDropper#257]
### Describe the solution you'd like

Зробіть більш темну кнопку і текст білим

**Comment by kepi** [comment]
Hello, can you please paste screenshot of which buttons you mean? The two top ones? Or all?

**Comment by kepi** [comment]
I belive this is fixed in latest version. Firefox addon is already published, Chrome will follow this or next week.

**Comment by maximus2526** [comment]
https://monosnap.com/file/WsoZAkLcsB4HLdIxhKARMqaDFxcU7d

Hello, the two top ones.  For better accessibility and readability, it’s
recommended to use a contrasting color, like white, for the text on dark
backgrounds

**Comment by kepi** [comment]
Thanks for clarification. In that case it is already fixed in latest version which is published for firefox and for some users on chrome. It will be rolled to all in about a week. Here is how it looks now:

![2024-10-30T19:22:44,605919833+01:00](https://github.com/user-attachments/assets/6196434a-6751-4d05-9489-039ccb98c43e)
