### ISSUE TITLE
Instant auto-save

### ISSUE THREAD

**Issue by ompatel2019** [kepi/chromeEyeDropper#265]
### Is your feature request related to a problem?

When I put the dropper on a colour and left click I have to go back to the plug in and click on copy hex-code or other form of color description. 

### Describe the solution you'd like

Have a setting where we choose auto-copy and what format. Eg. 
I want to have auto-copy on for its hex-code so whenever I click on a colour with this option on it will automatically save the colour to my clipboard and I can copy paste it anywhere. 

(Really useful for UI/UX designs)

**Comment by kepi** [comment]
HI @ompatel2019, thanks for your report.

Can you please check the extension options, if you have *Copy to clipboard* enabled? If you are on Chrome, it should be at this adress (or right click extension icon and choose *Options*)

`chrome-extension://gmdmdbohojkpaalkhklmnbicnmdlebnm/options.html`

It should look like this:

![image](https://github.com/user-attachments/assets/70f1bd71-4285-494f-a3cf-b9a6c2a08eea)

I believe it isn't on by default because it might overwrite something important in the clipboard, but I'm thinking about improving onboarding or changing this default for some time.

Btw. support to automatically copy other formats is planned.

**Comment by kepi** [comment]
Closing as no details provided.
