### ISSUE TITLE
Can't pick color

### ISSUE THREAD

**Issue by np6176a** [kepi/chromeEyeDropper#82]
the picker is always showing black

**Comment by TalkingCloaca** [comment]
Same issue here as well, I have not been able to make this work

Chrome build: 49.0.2623.47 beta

**Comment by kepi** [comment]
What operating system and version are you using? What page are you trying this on? (even if it is on all pages, just give me one example so I can check it). Thanks.

**Comment by TalkingCloaca** [comment]
Chrome OS 49.0.262347
using Eye Dropper ver. Version 0.3.7
and the websites it does not play nice seem arbitrary.  Ones that keep coming up are the Team Fortress 2 wiki, (https://wiki.teamfortress.com/wiki/Decorated) and 4chan (/k/ if it will help).  I am running an extension for 4chan (4chan X 1.11 and Namesync 4.9.1) and that may be causing the issue, I have not had the time to check.

**Comment by kepi** [comment]
@TalkingCloaca can you please try first load whole page on TF wiki and after it is fully loaded (spining wheel in favicon place in tab stops spining) try to use Eye Dropper?

I hit the problem when I tried to access that site and because it is loading really long time, like 10 seconds for me but it looks like fully rendered, I started Eye Dropper and saw black too. But when I wait untill page fully load it works without any problem.

**Comment by kbirstein** [comment]
Does not work on WIndows 10

**Comment by kepi** [comment]
@kbirstein can you please give me more details what exatly doesn't work for you? Can you please give me information about Chrome Version and which page you are trying it on?

**Comment by kbirstein** [comment]
It’s always black. Doesn’t pick up color.

**Comment by kepi** [comment]
I tried to reproduce this in multiple windows 10 installations without any sucess. Its always working.

Please, if this problem persist, create new issue with more details about your environment (Chrome version, operating system and version). Also specify example of page where it is not working. Thanks!
